Algoritmo "calculoDoProdutoESomaDosValores"
// Disciplina   : Lógica de prohramação com Javascript
// Professor   : Jailson 
// Descrição   : ler valores e calcular resultados do valor 1 e 3 e 2 e 4
// Autor(a)    : Tâmara
// Data atual  : 26/09/2022
Var

valor1,valor2,valor3,valor4,produto,soma:inteiro
 inicio
  escreval("Digite o primeiro valor: ")
leia(valor1)
escreval("Digite o segundo valor: ")
leia(valor2)
escreval("Digite o terceiro valor: ")
leia(valor3)
escreval("Digite o quarto valor: ")
leia(valor4)

produto<-valor1*valor3
soma<-valor2+valor4

escreval("o resultado do produto corresponde a: ",produto)

escreval("o resultado da soma do segundo e quarto valor é: ",soma)

fimalgoritmo