Algoritmo "testeCracter"
// Disciplina   : [Logica de programação com javascript]
// Professor   : jailson
// Descrição   : Teste Caracter
// Autor(a)    : Tâmara
// Data atual  : 05/09/2022
Var
// Seção de Declarações das variáveis
nome:caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o seu nome")
leia(nome)
escreval("O nome digitado é: ", nome)


Fimalgoritmo